<?php

namespace Jan\ZadanieBundle\Repository;
use Jan\ZadanieBundle\Entity\Items;

/**
 * ItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByAmountFilter(array $filters){        
        $query = $this->createQueryBuilder('i');

        if ($filters['gtamount'] !== null) {
        $query
            ->andWhere('i.amount > :gtamount')
            ->setParameter('gtamount', $filters['gtamount']);
        }
        if ($filters['amount'] !== null) {
            $query
                ->andWhere('i.amount = :amount')
                ->setParameter('amount', $filters['amount']);
        }

        return $query->getQuery()->getResult();
    }
}
